### ISSUE TITLE
Separating notification-callbacks from references

### ISSUE THREAD

**Issue by DHager** [pinepain/php-ref#4]
While `new \Weak\Reference($target,function(){...})` is certainly a nice shortcut, I expect that callbacks won't (and shouldn't) be used very much compared to just the weak-reference itself, and the callbacks can complicate:
1. Explaining to people that two `\Weak\Reference` objects are loosely-equal even when constructed with different callbacks
2. The issue of double-callbacks when cloning a `\Weak\Reference`

Now, I don't know how easy this would be to implement, but what about breaking out the responsibility for callback-management out into a new `\Weak\Notifier` object that can be _shared_ across `\Weak\Reference` instances that have the same referent?

``` PHP
$obj = new stdClass();

// Constructor no longer supports second argument
$ref = new \Weak\Reference($obj);

// Instead, it exposes a notifier-object
$notifier = $ref->getNotifier(); 
assert($notifier instanceof \Weak\Notifier);

// References that point to the same object will return the same notifier
$ref2 = new \Weak\Reference($obj);
$notifier2 = $ref2->getNotifier();
assert($notifier === $notifier2);

// The notifier is what supports adding callbacks
assert($notifier->isValid());
assert($notifier->numCallbacks() == 0);
$notifier->addCallback(function(){});
assert($notifier->numCallbacks() == 1);

// Nobody will have any reason to be surprised by this loose-quality anymore
assert($ref1 == $ref2); 

// You can allow cloning of References...
$ref3 = clone $ref; 

// But disallow cloning of the notifier to avoid duplicate-callbacks
$notifier3 = clone $notifier; // Fatal error
```

And just to be explicit about how Notifiers are per-referent:

``` PHP
$foo = new stdClass();
$bar = new stdClass();

$fooRef = new \Weak\Reference($foo);
$barRef = new \Weak\Reference($bar);

assert($fooRef != $barRef);
assert($fooRef->getNotifier() !== $barRef->getNotifier());

$n = new \Weak\Notifier(); // Fatal error, stub will show a private __construct() 
```

**Comment by pinepain** [comment]
What is your use case for bare weak reference?

**Comment by DHager** [comment]
One scenario is keeping a collection of listeners/subscribers/observers without holding a strong-reference that keeps them in-scope when nothing else is using them:

``` PHP
class Thingy{
    /**
     * @var \Weak\Reference[] A collection of references to ThingyListener instances
     */
    private $listeners = array();
    public function addListener(ThingyListener $l){
        $this->listeners[] = new Reference($l);
    }

    protected function dispatchEvent($evt){
        foreach($this->listeners as $ref){
            $listener = $ref->get();
            if(!is_null($listener)){        
                $listener->eventOccured($evt);
            }
        }
    }
}   
```

**Comment by pinepain** [comment]
Don't get it, but notify callback doesn't prevent you to do so. Weak references by itself are not very handy in PHP, I guess. Once again, my goal was to add notify-based approach, not poll-based.

**Comment by pinepain** [comment]
BTW, `Weak\Reference` constructor signature is `public function __construct(object $referent, callable $notify = null)`, notify callback is optional.

**Comment by DHager** [comment]
Correct, I'm not saying to remove the feature, but that moving its API to another class may improve the semantics of `Reference`.

Right now, the PHP API implies that each `\Weak\Reference` **individually owns** the callback you pass in, so that this code...

``` PHP
$ref1 = new \Weak\Reference($obj,$callback1);
$ref2 = new \Weak\Reference($obj,$callback2);
$ref3 = new \Weak\Reference($obj,$callback3);
$ref4 = new \Weak\Reference($obj,$callback4);
```

Suggests this is happening: ![Diagram](http://i.imgur.com/MKgZOzF.png)

People will assume that `$ref1 != $ref2` because they are pointing at different callbacks.

As an alternative, what about this:

``` PHP
$ref1 = new \Weak\Reference($obj);
$ref2 = new \Weak\Reference($obj);
$ref3 = new \Weak\Reference($obj);
$ref4 = new \Weak\Reference($obj);

$notifier = $ref1->getTargetNotifier();

$notifier->addCallbacks([$callback1,$callback2,$callback3,$callback4]);
```

Where the model is more like: ![Diagram](http://i.imgur.com/cdrWPGh.png)

This way it's "obvious" that `$ref1==$ref2`, and it implies it's safe to `clone $ref1` as long as you do not `clone $notifier`.

**Comment by pinepain** [comment]
I follow python's [weakref.ref](https://docs.python.org/3.5/library/weakref.html#weakref.ref) idea. What you propose to do can be done on top of what already exists.

I agree on note about comparing & clone are not very obvious and clear at some point and looking forward to fix that.

**Comment by DHager** [comment]
My default thinking is more like Java's, where you can optionally tell a [`WeakReference`](https://docs.oracle.com/javase/8/docs/api/java/lang/ref/WeakReference.html) that it should report to an interested [`ReferenceQueue`](https://docs.oracle.com/javase/8/docs/api/java/lang/ref/ReferenceQueue.html), which can be efficiently polled and used as the "heart" of whatever kinds of cleanup or callback tasks are needed.

A big concern I have with the Python style (storing the "extra behavior" onto the reference itself) -- is that those callbacks will fail to execute if their specific weak-reference is reclaimed _first_.

``` Python
import weakref

class Foo:
    pass

def callbackA(deadRef):
    print "Triggered A with", deadRef

obj = Foo()
ref = weakref.ref(obj,callback)
del ref # Whoops, the weak-reference went away first
del obj # Callback never happens!
```

**Comment by pinepain** [comment]
> A big concern I have with the Python style (storing the "extra behavior" onto the reference itself) -- is that those callbacks will fail to execute if their specific weak-reference is reclaimed first.

This is by-design so. I guess Java handles this the same way.

PR #5 addresses issue with loose comparison which was too loose. That PR also adds functionality to retrieve and change weakref notifier, which now can be `array`, like Java's ReferenceQueue. 

`Weak\Reference` provides now complete minimal abstraction which allows to build any kind of abstractions on top of it.

**Comment by DHager** [comment]
> This is by-design so. I guess Java handles this the same way.

Java should not have the same problems, because the `ReferenceQueue` maintains a link to all the `WeakReference` entities, keeping them from being GCed until they've been "dealt with" somehow and removed from the queue.  The `ReferenceQueue` itself is kept alive by... well, by whatever chain of events is calling `myRefQueue.poll()` and doing things with the results.

I just think it's a lot harder to accidentally shoot yourself in the foot.

> That PR also adds functionality to retrieve and change weakref notifier, which now can be array, like Java's ReferenceQueue.

I'm not so much concerned with queues/lists, but with how easily someone might accidentally let the `\Weak\Reference` to go out of scope and "lose" callbacks. For example, I'm not sure if this code will reliably print:

``` PHP

function VeryImportantThing(){
    echo("Phew! This was very important and had to happen.");
}

function ScheduleImportantCleanup($obj, $list){
    $ref = new \Weak\Reference($obj, function(){
        VeryImportantThing();
    });
    $ref2 = new \Weak\Reference($obj, $list); // Redundant?
}

$a = array();
$o = new stdClass();
ScheduleImportantCleanup($o, $list);
unset($o); 
sleep(1); 

// Before the script ends entirely, was anything printed?
```

**Comment by pinepain** [comment]
> For example, will this code reliably print a message?

No, destructors are not reliable, see [When will __destruct not be called in PHP?](http://stackoverflow.com/questions/2385047/when-will-destruct-not-be-called-in-php) SO thread.

I've added `array` notifier mechanism, but it also doesn't cover 100% cases. To run notifier with close to 100% guarantee `free_obj` handler should be used, but I suppose it's bad idea to mess with GC.

**Comment by DHager** [comment]
What I mean is, will `VeryImportantThing()` run at least ~90% of the time? Or do I need to manually keep a reference to `$ref2` indefinitely?

**Comment by pinepain** [comment]
Will your code shutdown in a proper, not unclean way at least ~90% of the time? Note, that even `array` doesn't guarantee it will be called. When unclean shutdown happen destructors are not called, but I can't say that any other code runs at that time too.

**Comment by DHager** [comment]
I'm not at all concerned about unclean shutdowns. After reviewing the Python-model I'm worried about how easily the user can introduce a lifecycle-bug that silently cancels all their callbacks during regular program flow.

**Comment by pinepain** [comment]
I guess at this point it is goes behind of this extension responsibility. User can introduce anything no one even hear about ever. Basically, that's why it worth for users to read docs first. Also, weak references in PHP is not what is common in every day usage, so it dramatically reduce number of this extension actual users, who probably will be familiar enough with PHP to understand what they are doing. But I'm totally agree with the point that it is possible introduce hard to investigation and non-obvious bugs with weak references.

**Comment by DHager** [comment]
So far we've talked about two strategies:
1. The user must remember to store every individual reference for longer than the lifetime of their referents if they want a particular callback to work (Python `weakref`)
2. The user is given a framework for remembering important references, polling them, and triggering cleanup

How about a third: Since we truly are dealing with global state (the GC and memory model) what about having some static storage on `\Weak\Reference` that automatically contains instances that are created with callbacks? 

``` PHP
$callback = function(){...};
$obj = StdClass();

assert(\Weak\Reference::CallbackCount() == 0);
$plainRef = new \Weak\Reference($obj);

// Still zero because we don't need to remember
// references that don't have callbacks
assert(\Weak\Reference::CallbackCount() == 0);

$ref = new \Weak\Reference($obj,$callback);
assert(\Weak\Reference::PendingCount() == 1);

unset($ref); 
assert(\Weak\Reference::PendingCount() == 1); // $ref is still alive in here

unset($obj); // Trigger the callback
assert(\Weak\Reference::PendingCount() == 0); // Callback occurred, Reference removed from list
```

Alternately, make the relationship explicit:

``` PHP
$callback = function(){...};
$obj = StdClass();

$ref = new \Weak\Reference($obj); // Note, no second-argument
\Weak\Reference::ScheduleCallback($ref,$callback);
```

**Comment by DHager** [comment]
Option number 4: User has to remember objects, but they're at least different objects from plain weak references, so that there's better separation-of-concerns:
- \Weak\Reference
  - Purpose: Provide a weak-handle to an object. That's all.
  - If GCed: No side-effects.
  - Loose equality: Only if both point to the same object. (What if object is gone?)
  - Cloning: Allowed
- \Weak\Trigger
  - Purpose: Waits to trigger a callback
  - Instantiated with a custom-callback and a weak-reference
  - No effect if weak-reference is already dead
  - Can be manually triggered by user (once only)
  - Can be canceled (if not already run)
  - If GCed, callback does _not_ occur.
  - If multiple similar copies created, callback will occur multiple times
  - Loose equality: Only if References are loosely-equal and if callbacks are equal
  - Cloning: Allowed

In code-form:

``` PHP
$callback = function(){...};
$obj = StdClass();

$ref = new \Weak\Reference($obj); // Only one argument
/** @var $trigger \Weak\Trigger **/
$trigger = new \Weak\Trigger($ref, $cb);
assert(!$trigger->wasRun());

$ref = null; // Forgot the weakref, but that's OK, it has no side-effects itself

assert(!$trigger->wasRun());
$obj = null; // Clear target
assert($trigger->wasRun());
```

**Comment by pinepain** [comment]
Hi! Thanks for your suggestions.

All specified above addresses higher abstraction level than this extension provides and may be done on top of existent extension functionality, e.g. as a standalone library or inside one's project, if it required.
